const actionTypes = {
  FETCH_MOVIES_START: 'FETCH_MOVIES_START',
  FETCH_MOVIES_SUCCESS: 'FETCH_MOVIES_SUCCESS',
  FETCH_MOVIES_FAILURE: 'FETCH_MOVIES_FAILURE',

  DELETE_MOVIE_START: 'DELETE_MOVIE_START',
  DELETE_MOVIE_SUCCESS: 'DELETE_MOVIE_SUCCESS',
  DELETE_MOVIE_FAILURE: 'DELETE_MOVIE_FAILURE',

  EDIT_MOVIE_START: 'EDIT_MOVIE_START',
  EDIT_MOVIE_SUCCESS: 'EDIT_MOVIE_SUCCESS',
  EDIT_MOVIE_FAILURE: 'EDIT_MOVIE_FAILURE',

  CREATE_MOVIE_START: 'CREATE_MOVIE_START',
  CREATE_MOVIE_SUCCESS: 'CREATE_MOVIE_SUCCESS',
  CREATE_MOVIE_FAILURE: 'CREATE_MOVIE_FAILURE',

  FETCH_MOVIE_DETAILS_START: 'FETCH_MOVIE_DETAILS_START',
  FETCH_MOVIE_DETAILS_SUCCESS: 'FETCH_MOVIE_DETAILS_SUCCESS',
  FETCH_MOVIE_DETAILS_FAILURE: 'FETCH_MOVIE_DETAILS_FAILURE',

  FETCH_MOVIE_TO_EDIT_START: 'FETCH_MOVIE_TO_EDIT_START',
  FETCH_MOVIE_TO_EDIT_SUCCESS: 'FETCH_MOVIE_TO_EDIT_SUCCESS',
  FETCH_MOVIE_TO_EDIT_FAILURE: 'FETCH_MOVIE_TO_EDIT_FAILURE',

  RESET_MODALS_STATE: 'RESET_MODALS_STATE',
};

export default actionTypes;
